// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgfwV8L2RNUfM2TAmt2_UnyoseteF4iaY',
    appId: '1:791241166671:web:809f616540155e84077f3a',
    messagingSenderId: '791241166671',
    projectId: 'nau-bot',
    authDomain: 'nau-bot.firebaseapp.com',
    storageBucket: 'nau-bot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVK7O6RlLKvNFpm2cpJxhnkfcExRjUs3c',
    appId: '1:791241166671:android:e477a4993d9d32f3077f3a',
    messagingSenderId: '791241166671',
    projectId: 'nau-bot',
    storageBucket: 'nau-bot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFkT1Y_Wbjac6RISFaRUIzJrFxISde4E',
    appId: '1:791241166671:ios:43232cfceb11ed90077f3a',
    messagingSenderId: '791241166671',
    projectId: 'nau-bot',
    storageBucket: 'nau-bot.appspot.com',
    iosClientId: '791241166671-5skb5cb590qua8gdtstck13n4fik3jks.apps.googleusercontent.com',
    iosBundleId: 'com.example.nau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFkT1Y_Wbjac6RISFaRUIzJrFxISde4E',
    appId: '1:791241166671:ios:9d7a19e850142b88077f3a',
    messagingSenderId: '791241166671',
    projectId: 'nau-bot',
    storageBucket: 'nau-bot.appspot.com',
    iosClientId: '791241166671-ihcampkr1qksevelutj7v5l4gosa4vkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.nau.RunnerTests',
  );
}
